/** reference/publishing/screens/*.html → Next.js routes */
export const PUB_HREF_MAP: Record<string, string> = {
  "home.html": "/",
  "community.html": "/",
  "community-post.html": "/",
  "community-write.html": "/community/write",
  "group.html": "/group",
  "group-find.html": "/group/find",
  "group-none.html": "/group",
  "record.html": "/record/new",
  "record-detail.html": "/record/new",
  "record-edit.html": "/record/new",
  "my.html": "/my",
  "my-settings.html": "/my/settings",
  "my-badges.html": "/my/badges",
  "search.html": "/search",
  "notifications.html": "/notifications",
  "schedule-write.html": "/group/schedule/new",
  "schedule-detail.html": "/group/schedule/new",
  "user-profile.html": "/users/demo",
  "weswim_badge_guide.html": "/guide/badges",
  "login.html": "/login",
  "signup.html": "/signup",
  "signup-complete.html": "/signup",
};
